# Generated by Django 2.2.2 on 2019-06-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190607_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='numb',
        ),
    ]
